In [ ]:
import configparser
from datetime import datetime, timedelta
import os
import sys
import pandas as pd

In [3]:
import pandas as pd

In [9]:
tools_df = pd.read_json('D:/hieulon.json')
tools_df = tools_df[tools_df['category']=='Data Gorvernance']
tools_df = tools_df[tools_df['category']!='Business Intelligence (BI)']
tools_df = tools_df[tools_df['category']!='Workflow Orchestration']
tools_df = tools_df.sort_values(by=['category'])
tools_df.head(50)

,name,category,countCompanies,Stage,Target Segment,Deployment,Business Model,Pricing,Location
219,Kausa,Augmented Analytics,0,Early Stage,Mid size / Enterprise,Open source,Open Source,Contact Sales,"Berlin, Germany"
127,debezium,Change Data Capture,1,Late Stage,Mid size,Open source,Open Source,Freemium,US
28,Apache Atlas,Data Cataloging,1,Mid Stage,Enterprise,Open source,Open Source,Freemium,US
245,Marquez,Data Cataloging,0,Mid Stage,Mid size,On Prem,Open Source,Freemium,US
22,Amundsen,Data Discovery,2,Early Stage,Mid size,On Prem,Open Source,Free trial,US
290,Open Data Discovery,Data Discovery,0,Early Stage,Mid Size / Enterprise,Open Source,Open Source,Freemium,US
234,Lakefs,Data Lakes,0,Early Stage,Mid size,Open source,Open Source,Freemium,"Tel Aviv, Israel"
31,Apache Hudi,Data Lakes,2,Early Stage,Mid Size / Enterprise,Open Source,Open Source,Freemium,"California, US"
230,Kylo,Data Lakes,0,Mid Stage,Enterprise,SaaS,Open Source,Freemium,"California, US"
130,Delta.io,Data Lakes,3,Mid Stage,Enterprise / Mid size,SaaS / On Prem,Open Source,Free trial,US
458,whylabs,Data Logging,0,Early Stage,Mid size / Enterprise / SMBs,Open source,Open Source,Freemium,"Seattle, US"
378,Snowplow,Data Logging,6,Late Stage,Mid size / Enterprise,Open source,Open Source,Freemium,"London, England"
35,Apache Spark,Data Modelling and Transformation,5,Late Stage,Mid Size / Enterprise,On Prem,Open Source,Freemium,US
126,dbt,Data Modelling and Transformation,100,Early Stage,Enterprise / Mid size,SaaS,Open Source,Free trial / Contact Sales,US
336,re_data,Data Quality Monitoring,0,Early Stage,Enterprise / Mid size / SMBs,Open source,Open Source,Freemium,"Warsaw, Poland"
181,Griffin,Data Quality Monitoring,0,Mid Stage,Enterprise / Mid size,On Prem,Open Source,Freemium,US
177,Great Expectations,Data Quality Monitoring,2,Early Stage,Mid size,On Prem,Open Source,Freemium,"California, US"
140,Elementary Data,Data Quality Monitoring,0,Early Stage,Mid Size,Open Source,Open Source,Freemium,US
30,Apache Griffin,Data Quality Monitoring,0,Early Stage,Mid size,Open source,Open Source,Not Available,"Houston, Texas, US"
246,Materialize,Data Streaming,1,Late Stage,Enterprise / Mid size,On Prem,Open Source,Freemium,"New York, US"
184,hazelcast,Data Streaming,0,Late Stage,Enterprise / Mid size,SaaS / On Prem,Open Source,Freemium,"California, US"
36,Apache Storm,Data Streaming,5,Late Stage,Enterprise / Mid size,On Prem,Open Source,Freemium,US
227,KsqlDB,Data Streaming,0,Early Stage,Mid size,Open source,Open Source,Freemium,"California, US"
32,Apache Kafka,Data Streaming,18,Late Stage,Enterprise / Mid size,On Prem,Open Source,Freemium,US
29,Apache Flink,Data Streaming,4,Late Stage,Enterprise / Mid size,On Prem,Open Source,Freemium,US
349,Samza,Data Streaming,0,Early Stage,Mid size / Enterprise,Open source,Open Source,Not Available,"Wakefield, Massachusetts, U.S."
192,Hive,Data Warehouses,1,Late Stage,Mid Size / Enterprise,On Prem,Open Source,Freemium,US
333,Querybook,Data Workspace/ Collaboration,0,Mid Stage,Mid size / Enterprise,Open source,Open Source,Freemium,US
369,Singer,ETL Tools,0,Early Stage,Mid Size / Enterprise,Open Source,Open Source,Freemium,US
281,Nunchi Studio,ETL Tools,0,Early Stage,Mid Size,Open Source,Open Source,Contact Sales,"Paris, France"
255,Metorikku,ETL Tools,1,Early Stage,Mid Size,Open Source,Open Source,Freemium,"New York, US"
10,Airbyte,ETL Tools,3,Early Stage,Enterprise / Mid size,SaaS,Open Source,Contact Sales,"San Francisco, US"
249,Meltano,ETL Tools,3,Early Stage,Mid size / Enterprise,Open source,Open Source,Freemium,US
195,hopsworks,Feature Store,0,Early Stage,Mid size / Enterprise,SaaS,Open Source,Freemium / Contact Sales,Sweden
265,Molecula,Feature Store,3,Mid Stage,Mid size / Enterprise,SaaS,Open Source,Contact Sales,"Texas, US"
154,Feast,Feature Store,0,Early Stage,Enterprise,SaaS,Open Source,Free trial,"California, US"
202,iguazio,Feature Store,3,Mid Stage,Mid size / Enterprise,SaaS,Open Source,Free trial / Contact Sales,"Herzliya, Israel"
257,MetriQL,Metrics Store,0,Early Stage,Mid size,SaaS / Open source,Open Source,Freemium,US
272,N8N,No code automation,0,Early Stage,Mid size,On Prem / SaaS,Open Source,Freemium,Berlin
223,Kimball,PLG CRM,0,Early Stage,Mid size,On Prem,Open Source,Contact Sales,"Philadelphia, US"
316,Post Hog,Product Analytics,1,Early Stage,Enterprise / Mid size,Open source,Open Source,Freemium / Contact Sales,"San Francisco, California"
282,Objectiv,Product Analytics,0,Mid Stage,Mid Size,Open Source,Open Source,Free,"Utrecht, Netherlands"
78,Castled,Reverse ETL Tools,0,Early Stage,SMBs / Mid size,SaaS,Open Source,Free trial,India
441,Twinify,Synthetic Data,0,Early Stage,Mid size,Open source / On Prem,Open Source,Freemium,US
178,Gretel Synthetic,Synthetic Data,0,Early Stage,Mid size,Open source / On Prem,Open Source,Freemium,"San Diego, California, US"
374,Smart Noise,Synthetic Data,0,Early Stage,Mid size,On Prem / Open source,Open Source,Freemium,US
405,Synner,Synthetic Data,0,Mid Stage,Mid size,Open source / On Prem,Open Source,Freemium,US
407,Synth,Synthetic Data,0,Early Stage,Mid size,Open source / On Prem,Open Source,Freemium,US
408,Synthea,Synthetic Data,0,Early Stage,Mid size,Open source,Open Source,Freemium,US
210,Instill Ai,Synthetic Data,0,Early Stage,Mid size,Open source,Open Source,Freemium,US

In [5]:
results = tools_df[tools_df['category'] == 'Data Cataloging']
results = results[results['Business Model']=='Open Source']
results.head(20)

,name,category,countCompanies,Stage,Target Segment,Deployment,Business Model,Pricing,Location
28,Apache Atlas,Data Cataloging,1,Mid Stage,Enterprise,Open source,Open Source,Freemium,US

In [6]:
results.head()

,name,category,countCompanies,Stage,Target Segment,Deployment,Business Model,Pricing,Location
28,Apache Atlas,Data Cataloging,1,Mid Stage,Enterprise,Open source,Open Source,Freemium,US

In [7]:
results = results[results['Business Model']=='Open Source']
results.head(20)

,name,category,countCompanies,Stage,Target Segment,Deployment,Business Model,Pricing,Location
28,Apache Atlas,Data Cataloging,1,Mid Stage,Enterprise,Open source,Open Source,Freemium,US

In [8]:
category_df = tools_df['category'].to_frame()
category_df = category_df.drop_duplicates(keep='first',inplace=False).reset_index(drop=True)
category_df.head(50)

                             category
0                 Change Data Capture
1                     Data Cataloging
2                      Data Discovery
3                          Data Lakes
4                        Data Logging
5   Data Modelling and Transformation
6             Data Quality Monitoring
7                      Data Streaming
8                     Data Warehouses
9                           ETL Tools
10                      Feature Store
11                  Product Analytics